### ISSUE TITLE
关于vmware后台运行

### ISSUE THREAD

**Issue by dysl357085918** [huataihuang/cloud-atlas-draft#2]
在cloud-atlas-draft/virtual/vmware/vmware_headless.md这个里面
找不到文件的原因是已经用了引号,遇到Virtual Machines.localized中间的空格不用\这个了

我这边是可以的

**Comment by huataihuang** [comment]
非常感谢指正，我已经修订了原文 [vmware_headless.md](https://github.com/huataihuang/cloud-atlas-draft/blob/master/virtual/vmware/vmware_headless.md)
