### ISSUE TITLE
openconnect 免输入 root 密码问题

### ISSUE THREAD

**Issue by awaken233** [huataihuang/cloud-atlas-draft#3]
https://github.com/huataihuang/cloud-atlas-draft/blob/2dd38f23f7ba5a1454876aa73feb6daf2f7424d8/security/vpn/openconnect/openconnect.md?plain=1#L69-L71

博主 我这里配置为什么不起作用， 还是需要输入root 密码？这可能还什么有关系呢？需要我提供一些什么额外信息帮助排查问题吗

**Comment by huataihuang** [comment]
配置中 %admin 表示是admin用户组的用户可以免密码使用 openconnect

你看看你自己是不是admin组用户

请输入

```bash
id
```

看看输出内容，正常情况下类似我如下输出

```
uid=505(admin) gid=505(admin) groups=505(admin),504(docker)
```

上面可以看到我自己的账号 gid 是 505 ，这个组就是 admin 组，也就是 /etc/sudoers 中配置的 ``%admin``

**Comment by awaken233** [comment]
谢谢解答， 我执行后的输出是

```
uid=501(ve) gid=20(staff) groups=20(staff),12(everyone),61(localaccounts),79(_appserverusr),80(admin),81(_appserveradm),98(_lpadmin),33(_appstore),100(_lpoperator),204(_developer),250(_analyticsusers),395(com.apple.access_ftp),398(com.apple.access_screensharing),399(com.apple.access_ssh),400(com.apple.access_remote_ae),701(com.apple.sharepoint.group.1)
```

我应该是属于是 admin 组吧？

**Comment by huataihuang** [comment]
是的，你的账号确实属于admin组

请在你的账号登陆下执行

```
sudo -l
```

另外，你看一下 /etc/sudoers

是不是重复配置了 %admin 配置行，是不是你的个人账号在这个配置 /etc/sudoers 配置文件中有多行匹配上了，多行配置是不是相互有冲突。如果重复匹配上你的账号，那么只有最后一行配置有效

**Comment by awaken233** [comment]
```
❯ sudo -l
Password:
Matching Defaults entries for ve on vdeMacBook-Pro:
    env_reset, env_keep+=BLOCKSIZE, env_keep+="COLORFGBG COLORTERM", env_keep+=__CF_USER_TEXT_ENCODING, env_keep+="CHARSET LANG LANGUAGE LC_ALL LC_COLLATE LC_CTYPE", env_keep+="LC_MESSAGES LC_MONETARY
    LC_NUMERIC LC_TIME", env_keep+="LINES COLUMNS", env_keep+=LSCOLORS, env_keep+=SSH_AUTH_SOCK, env_keep+=TZ, env_keep+="DISPLAY XAUTHORIZATION XAUTHORITY", env_keep+="EDITOR VISUAL", env_keep+="HOME MAIL",
    lecture_file=/etc/sudo_lecture

User ve may run the following commands on vdeMacBook-Pro:
    (ALL) ALL

```


这是我的配置

<img width="676" alt="image" src="https://github.com/user-attachments/assets/61efafe4-d9af-46bd-9182-ffb2a8512bd6" />

我是brew安装的,这样配置有问题吗

**Comment by huataihuang** [comment]
通过 `sudo -l` 可以看到，你的系统实际生效的只有如下这行权限，也就是每次 sudo 都需要密码(没有设置 `NOPASSWD` )

> User ve may run the following commands on vdeMacBook-Pro:
>    (ALL) ALL

`man sudoers` 的说明中有如下解释:

>      When multiple entries match for a user, they are applied in order.
>      Where there are multiple matches, the last match is used (which is not
>      necessarily the most specific match).

也是就是说，如果有多行 `/etc/sudoers` 配置匹配上一个用户，则规则是依次生效的。

如果有多个匹配项，那么使用最后一个匹配配置。

你的 `/etc/sudoers` 配置中，有两行关于 `admin` 组的，我在我的 macOS 上验证过了:

```
%admin		ALL = (ALL) NOPASSWD: /usr/local/bin/openconnect
%admin		ALL = (ALL) ALL
```

这个配置下执行 `sudo -l` 输出配置是

```
...
User huatai may run the following commands on 192:
    (ALL) NOPASSWD: /usr/local/bin/openconnect
    (ALL) ALL
```

此时执行 `sudo openconnect ...` 会提示需要输入密码，原因是后一条配置 `(ALL) ALL` 覆盖了前面配置的 `(ALL) NOPASSWD` ，即多个匹配项使用最后一个匹配配置。

解决的方法是修订 `/etc/sudoers` 配置中的配置顺序，即修改成

```
%admin          ALL = (ALL) ALL
%admin          ALL = (ALL) NOPASSWD: /usr/local/bin/openconnect
```

此时我再检查 `sudo -l` 输出内容就是:

```
User huatai may run the following commands on 192:
    (ALL) ALL
    (ALL) NOPASSWD: /usr/local/bin/openconnect
```

这样，其他需要 `sudo` 执行的系统命令依然会提示要密码，但是 `openconnect` 就不再需要密码，因为 `NOPASSWD: /usr/local/bin/openconnect` 在 `ALL` 后面，最后匹配的匹配项就会生效。

**请修改一下你的配置顺序** `正确的配置应该是

```
%admin		ALL = (ALL) ALL
%admin		ALL = (ALL) NOPASSWD: /usr/local/bin/openconnect
```

**Comment by awaken233** [comment]
👍🏻 非常感谢博主的耐心解答， 可以了，非常感谢
